export interface Artist {
  slug: string
  name: string
  nickname?: string
  startDate: string
  styles: string[]
  bio: string
  instagram?: string
  photo?: string
  styleLabel?: string
  subtitle?: string
  portfolio: { src: string; tag: string | string[]; label: string }[]
}

export function getYearsExperience(startDate: string): number {
  const start = new Date(startDate)
  const now = new Date()
  let years = now.getFullYear() - start.getFullYear()
  const m = now.getMonth() - start.getMonth()
  if (m < 0 || (m === 0 && now.getDate() < start.getDate())) years--
  return years
}

export const artists: Artist[] = [
  {
    slug: 'ally',
    name: 'Allison Mejía',
    nickname: 'Ally',
    startDate: '2019-07-01',
    styles: ['Ilustrativo', 'Blackwork', 'Línea fina', 'Color'],
    bio: 'Me llamo Ally, me gusta combinar distintos tamaños de línea. Tatuar a color es algo que me emociona mucho, en especial estilo kawaii y/o glitter.',
    instagram: 'https://www.instagram.com/ally.tattooist',
    photo: '/artistas/ally/profilepic.png',
    portfolio: [
      { src: '/artistas/ally/blackwork1.jpeg',   tag: 'blackwork',   label: 'Blackwork' },
      { src: '/artistas/ally/blackwork2.jpeg',   tag: 'blackwork',   label: 'Blackwork' },
      { src: '/artistas/ally/blackwork3.jpeg',   tag: 'blackwork',   label: 'Blackwork' },
      { src: '/artistas/ally/blackwork4.jpeg',   tag: 'blackwork',   label: 'Blackwork' },
      { src: '/artistas/ally/color1.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color2.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color3.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color4.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color5.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color6.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color7.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color8.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color9.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color10.jpeg',      tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/color11.jpeg',      tag: 'color',       label: 'Color' },
      { src: '/artistas/ally/ilustrativo1.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/ally/lineafina1.jpeg',   tag: 'linea-fina',  label: 'Línea fina' },
      { src: '/artistas/ally/lineafina2.jpeg',   tag: 'linea-fina',  label: 'Línea fina' },
      { src: '/artistas/ally/lineafina3.jpeg',   tag: 'linea-fina',  label: 'Línea fina' },
      { src: '/artistas/ally/lineafina4.jpeg',   tag: 'linea-fina',  label: 'Línea fina' },
    ],
  },
  {
    slug: 'stevan',
    name: 'Stevan Marroquín',
    startDate: '2012-01-01',
    styles: ['Neo Japonés', 'Neo Tradicional', 'Realismo', 'Cover Up'],
    bio: 'Fundé Soul\'s Anchor y estoy contento y agradecido con Dios por la oportunidad de dedicarme a hacer arte. Me gusta el neo japonés y el neo tradicional, pero siempre estoy experimentando con el realismo.',
    instagram: 'https://www.instagram.com/stevanmarroquintattoo',
    photo: '/artistas/stevan/profilepic.png',
    portfolio: [
      { src: '/artistas/stevan/japanese.JPG',    tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese1.png',   tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese2.png',   tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese3.png',   tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese4.png',   tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese5.png',   tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese6.png',   tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese7.png',   tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese8.png',   tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese9.png',   tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese10.png',  tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese11.png',  tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese12.png',  tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese13.png',  tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese14.png',  tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/japanese15.png',  tag: 'neo-japanese', label: 'Neo Japonés' },
      { src: '/artistas/stevan/neotrad.png',     tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/stevan/neotrad1.png',    tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/stevan/neotrad2.png',    tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/stevan/neotrad3.png',    tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/stevan/neotrad4.png',    tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/stevan/neotrad5.png',    tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/stevan/neotrad6.png',    tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/stevan/neotrad7.png',    tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/stevan/neotrad8.png',    tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/stevan/neorealismo.png',  tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/stevan/neorealismo1.png', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/stevan/neorealismo2.png', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/stevan/neorealismo3.png', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/stevan/neorealismo4.png', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/stevan/neorealismo5.png', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/stevan/neorealismo6.png', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/stevan/neorealismo7.png', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/stevan/neorealismo8.png', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/stevan/coverup.png',    tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup1.png',   tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup2.png',   tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup3.png',   tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup4.png',   tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup5.png',   tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup7.png',   tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup8.png',   tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup9.png',   tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup10.png',  tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup11.png',  tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup12.png',  tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup13.png',  tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup14.png',  tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup15.png',  tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup16.png',  tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup17.png',  tag: 'cover-up', label: 'Cover Up' },
      { src: '/artistas/stevan/coverup18.png',  tag: 'cover-up', label: 'Cover Up' },
    ],
  },
  {
    slug: 'chejo',
    name: 'Sergio Sosa',
    nickname: 'Chejo Sosa',
    startDate: '2013-02-01',
    styles: ['Ilustrativo', 'Color', 'Blackwork'],
    bio: 'Me gusta mucho el café, mi banda favorita es Korn, colecciono juguetes vintage y también sneakers. Me gusta mucho dibujar cosas surreales y diseños fuera de lo común.',
    instagram: 'https://www.instagram.com/chejososa',
    photo: '/artistas/chejo/profilepic.png',
    portfolio: [
      { src: '/artistas/chejo/blackwork.jpeg',    tag: 'blackwork',   label: 'Blackwork' },
      { src: '/artistas/chejo/color.jpeg',        tag: 'color',       label: 'Color' },
      { src: '/artistas/chejo/color2.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/chejo/color3.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/chejo/color4.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/chejo/color5.jpeg',       tag: 'color',       label: 'Color' },
      { src: '/artistas/chejo/ilustrativo.jpeg',  tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/chejo/ilustrativo2.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/chejo/ilustrativo3.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/chejo/ilustrativo4.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/chejo/ilustrativo5.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/chejo/ilustrativo6.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
    ],
  },
  {
    slug: 'jony',
    name: 'Jony Rodas',
    startDate: '2017-01-01',
    styles: ['Realismo', 'Black and Gray'],
    bio: 'Inicié en el mundo del tatuaje en enero del 2017 y desde entonces me he dedicado a crear piezas únicas, especializándome en black and gray, realismo y diseños personalizados. Me apasiona transformar ideas en arte, cuidando cada detalle para que cada tatuaje tenga identidad y significado.',
    instagram: 'https://www.instagram.com/jonyrodas',
    photo: '/artistas/jony/profilepic.png',
    portfolio: [
      { src: '/artistas/jony/realismo.jpeg',  tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/jony/realismo1.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/jony/realismo2.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/jony/realismo3.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/jony/realismo4.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/jony/realismo5.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/jony/realismo6.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/jony/realismo7.jpeg', tag: 'realismo', label: 'Realismo' },
    ],
  },
  {
    slug: 'zoldyck',
    name: 'José Pablo Centeno',
    nickname: 'Zoldyck',
    startDate: '2018-05-01',
    styles: ['Anime', 'Blackwork'],
    bio: 'Me llamo José Pablo Centeno, mejor conocido como Zoldyck — el apellido de uno de mis personajes favoritos de anime. Me dedico principalmente a tatuar anime en blackwork y black and grey, algunos con detalles a color, pero me gusta tatuar cualquier cosa en blackwork. Cuando agarré por primera vez una máquina no lo veía como algo que me diera para vivir, fue más un hobbie. Gracias a Dios, mi familia y amigos logré cumplir un sueño que no sabía que era mi sueño: vivir de algo que desde niño me apasiona, dibujar y crear.',
    instagram: 'https://www.instagram.com/zoldycktattoo',
    photo: '/artistas/zoldyck/profilepic.png',
    portfolio: [
      { src: '/artistas/zoldyck/DSC09335.jpeg',                             tag: ['anime', 'blackwork'], label: 'Anime' },
      { src: '/artistas/zoldyck/DSC09773.jpeg',                             tag: ['anime', 'blackwork'], label: 'Anime' },
      { src: '/artistas/zoldyck/DSC09784.jpeg',                             tag: ['anime', 'blackwork'], label: 'Anime' },
      { src: '/artistas/zoldyck/FE3386EB-4C9C-40D5-9447-9C4FC950560B.jpeg', tag: ['anime', 'blackwork'], label: 'Anime' },
      { src: '/artistas/zoldyck/IMG_0354.jpeg',                             tag: ['anime', 'blackwork'], label: 'Anime' },
      { src: '/artistas/zoldyck/IMG_6323.jpeg',                             tag: ['anime', 'blackwork'], label: 'Anime' },
      { src: '/artistas/zoldyck/IMG_6894.jpeg',                             tag: ['anime', 'blackwork'], label: 'Anime' },
      { src: '/artistas/zoldyck/IMG_8760.jpeg',                             tag: ['anime', 'blackwork'], label: 'Anime' },
    ],
  },
  {
    slug: 'omar',
    name: 'Omar Escobar',
    startDate: '2020-12-01',
    styles: ['Neo Tradicional', 'Neo Japonés', 'Tradicional', 'Realismo'],
    bio: 'Me especializo en el estilo Neo Tradicional y mi enfoque actual es perfeccionar mi técnica para entregar siempre mejores resultados.',
    instagram: 'https://www.instagram.com/omar.tattoos',
    photo: '/artistas/omar/profilepic.png',
    portfolio: [
      { src: '/artistas/omar/japanese.jpg',              tag: 'neo-japanese',   label: 'Neo Japonés' },
      { src: '/artistas/omar/japanase2.jpg',             tag: 'neo-japanese',   label: 'Neo Japonés' },
      { src: '/artistas/omar/neotradicional.jpg',        tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/omar/neotradicional2.jpg',       tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/omar/neotradicional3.jpg',       tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/omar/neotradicional4.JPG',       tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/omar/neotradicional5.JPG',       tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/omar/neotradicional6.jpg',       tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/omar/neotradicional7.jpg',       tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/omar/neotradicional8.JPG',       tag: 'neo-traditional', label: 'Neo Tradicional' },
      { src: '/artistas/omar/tradicional.jpg',           tag: 'tradicional',    label: 'Tradicional' },
      { src: '/artistas/omar/tradicional2.jpg',          tag: 'tradicional',    label: 'Tradicional' },
      { src: '/artistas/omar/tradicional3.jpg',          tag: 'tradicional',    label: 'Tradicional' },
      { src: '/artistas/omar/tradicional4.jpg',          tag: 'tradicional',    label: 'Tradicional' },
      { src: '/artistas/omar/tradicional5.jpg',          tag: 'tradicional',    label: 'Tradicional' },
      { src: '/artistas/omar/tradicional6.jpg',          tag: 'tradicional',    label: 'Tradicional' },
      { src: '/artistas/omar/tradicional7.jpg',          tag: 'tradicional',    label: 'Tradicional' },
      { src: '/artistas/omar/blackandgrayrealismo.jpg',  tag: 'realismo',       label: 'Realismo' },
      { src: '/artistas/omar/blackandgrayrealismo2.jpg', tag: 'realismo',       label: 'Realismo' },
      { src: '/artistas/omar/blackandgrayrealismo3.jpg', tag: 'realismo',       label: 'Realismo' },
    ],
  },
  {
    slug: 'matty',
    name: 'Matty Snx',
    startDate: '2020-02-01',
    styles: ['Tradicional'],
    bio: 'Nací en el Salvador y actualmente trabajo en Guatemala, mi enfoque principal es el estilo tradicional, pero siempre me mantengo experimentando en otros estilos, siempre priorizando diseños que perduren en el tiempo.',
    instagram: 'https://www.instagram.com/matty.ttts',
    photo: '/artistas/matty/profilepic.png',
    portfolio: [
      { src: '/artistas/matty/tradicional.jpeg',   tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional2.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional3.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional4.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional5.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional6.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional7.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional8.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional9.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional10.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional11.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional12.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional13.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional14.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional15.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional16.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional17.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional18.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional19.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/matty/tradicional20.jpeg', tag: 'tradicional', label: 'Tradicional' },
    ],
  },
  {
    slug: 'pepe',
    name: 'Mario Mejía',
    nickname: 'Pepe',
    startDate: '2019-02-01',
    styles: ['Línea fina', 'Realismo'],
    bio: 'Me considero una persona carismática, platicadora y amigable. Convertir una sesión de tatuaje en una plática amena es algo que me llena — pasarla bien y disfrutar haciendo lo que me gusta junto a mis clientes es algo que no cambiaría. Siempre enfocado en seguir aprendiendo y mejorando para poder dar lo mejor de mí en cada sesión, especializándome en línea fina y realismo.',
    instagram: 'https://www.instagram.com/pepetattooist',
    photo: '/artistas/pepe/profilepic.png',
    portfolio: [
      { src: '/artistas/pepe/IMG_0306.jpeg',   tag: 'linea-fina', label: 'Línea fina' },
      { src: '/artistas/pepe/IMG_0779.jpeg',   tag: 'linea-fina', label: 'Línea fina' },
      { src: '/artistas/pepe/IMG_1539.jpeg',   tag: 'linea-fina', label: 'Línea fina' },
      { src: '/artistas/pepe/IMG_1945.jpeg',   tag: 'linea-fina', label: 'Línea fina' },
      { src: '/artistas/pepe/IMG_2046.jpeg',   tag: 'linea-fina', label: 'Línea fina' },
      { src: '/artistas/pepe/IMG_2259.jpeg',   tag: 'linea-fina', label: 'Línea fina' },
      { src: '/artistas/pepe/IMG_2963.jpeg',   tag: 'linea-fina', label: 'Línea fina' },
      { src: '/artistas/pepe/IMG_2984.jpeg',   tag: 'linea-fina', label: 'Línea fina' },
      { src: '/artistas/pepe/IMG_3946.jpeg',   tag: 'realismo',   label: 'Realismo' },
      { src: '/artistas/pepe/IMG_4726.jpeg',   tag: 'realismo',   label: 'Realismo' },
      { src: '/artistas/pepe/IMG_6091.jpeg',   tag: 'realismo',   label: 'Realismo' },
      { src: '/artistas/pepe/IMG_6091_1.jpeg', tag: 'realismo',   label: 'Realismo' },
      { src: '/artistas/pepe/IMG_6328.jpeg',   tag: 'realismo',   label: 'Realismo' },
      { src: '/artistas/pepe/IMG_6861.jpeg',   tag: 'realismo',   label: 'Realismo' },
      { src: '/artistas/pepe/IMG_7438.jpeg',   tag: 'realismo',   label: 'Realismo' },
      { src: '/artistas/pepe/IMG_7926.jpeg',   tag: 'realismo',   label: 'Realismo' },
    ],
  },
  {
    slug: 'leo',
    name: 'Leonardo Ramijak',
    nickname: 'Polaco',
    startDate: '2014-05-01',
    styles: ['Tradicional', 'Blackwork', 'Línea fina'],
    bio: 'Soy argentino, llevo 8 años viajando y recorrí 23 países en ese tiempo. Ahora instalado en Guatemala.',
    instagram: 'https://www.instagram.com/polaco_ramijak',
    photo: '/artistas/leo/profilepic.png',
    portfolio: [
      { src: '/artistas/leo/tradicional.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/leo/tradicional2.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/leo/tradicional3.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/leo/tradicional4.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/leo/tradicional5.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/leo/tradicional6.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/leo/tradicional7.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/leo/tradicional8.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/leo/fineline.jpeg',     tag: 'linea-fina',  label: 'Línea fina' },
      { src: '/artistas/leo/fineline2.jpeg',    tag: 'linea-fina',  label: 'Línea fina' },
    ],
  },
  {
    slug: 'pablo',
    name: 'Pablo Cardona',
    startDate: '2022-07-01',
    styles: ['Tradicional', 'Ilustrativo', 'Línea fina'],
    bio: 'Me gusta trabajar el tradicional americano y experimentar con el tradicional europeo. También me gustan los tatuajes finos, estéticamente elegantes. Me gusta salir de mi zona de confort, conocer y aprender de nuevos estilos, siempre comprometido en un resultado espectacular.',
    instagram: 'https://www.instagram.com/cardona_tattoo.8',
    photo: '/artistas/pablo/profilepic.png',
    portfolio: [
      { src: '/artistas/pablo/tradicional.jpeg',   tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional1.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional2.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional3.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional4.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional5.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional6.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional7.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional8.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional9.jpeg',  tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional10.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/tradicional11.jpeg', tag: 'tradicional', label: 'Tradicional' },
      { src: '/artistas/pablo/ilustrativo.jpeg',   tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/pablo/ilustrativo1.jpeg',  tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/pablo/ilustrativo2.jpeg',  tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/pablo/ilustrativo3.jpeg',  tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/pablo/lineafina.jpeg',     tag: 'linea-fina',  label: 'Línea fina' },
      { src: '/artistas/pablo/lineafina1.jpeg',    tag: 'linea-fina',  label: 'Línea fina' },
      { src: '/artistas/pablo/lineafina2.jpeg',    tag: 'linea-fina',  label: 'Línea fina' },
      { src: '/artistas/pablo/lineafina3.jpeg',    tag: 'linea-fina',  label: 'Línea fina' },
    ],
  },
  {
    slug: 'focho',
    name: 'Cristopher Enríquez',
    nickname: 'Focho',
    startDate: '2014-08-01',
    subtitle: 'Perforador',
    styleLabel: 'Estilos de piercing',
    styles: ['Oreja', 'Nariz', 'Ceja', 'Labio', 'Ombligo'],
    bio: 'Soy de Quito, Ecuador y me mudé a Guatemala en 2023. Mi intención es elevar los estándares de bioseguridad y el nivel de la alta joyería.',
    instagram: 'https://www.instagram.com/focho_tp',
    photo: '/artistas/focho/profilepic.png',
    portfolio: [
      { src: '/artistas/focho/oreja.jpg',    tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja2.jpg',   tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja3.jpg',   tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja5.jpg',   tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja6.jpg',   tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja7.jpg',   tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja8.jpg',   tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja9.heic',  tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja10.heic', tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja11.heic', tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja12.heic', tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/oreja13.heic', tag: 'oreja',   label: 'Oreja' },
      { src: '/artistas/focho/nariz.jpg',    tag: 'nariz',   label: 'Nariz' },
      { src: '/artistas/focho/nariz2.jpg',   tag: 'nariz',   label: 'Nariz' },
      { src: '/artistas/focho/nariz3.heic',  tag: 'nariz',   label: 'Nariz' },
      { src: '/artistas/focho/nariz4.heic',  tag: 'nariz',   label: 'Nariz' },
      { src: '/artistas/focho/ceja.jpg',     tag: 'ceja',    label: 'Ceja' },
      { src: '/artistas/focho/ceja2.heic',   tag: 'ceja',    label: 'Ceja' },
      { src: '/artistas/focho/labio.jpg',    tag: 'labio',   label: 'Labio' },
      { src: '/artistas/focho/ombligo.jpg',  tag: 'ombligo', label: 'Ombligo' },
    ],
  },
  {
    slug: 'sofy',
    name: 'Sofy',
    startDate: '2022-10-01',
    subtitle: 'Jewelry Specialist',
    styleLabel: 'Estilos de piercing',
    styles: ['Oreja', 'Nariz'],
    bio: 'Jewerly Specialist con 4 años de experiencia en la industria del body piercing y la joyería corporal. Su trabajo combina técnica, estética y atención personalizada para crear proyectos que respeten la anatomía, el estilo y el proceso de cada cliente. Su enfoque se caracteriza por ofrecer un servicio cercano, detallista y profesional, enfocado en la calidad y la confianza.',
    instagram: 'https://www.instagram.com/sofysophs',
    photo: '/artistas/sofy/profilepic.png',
    portfolio: [
      { src: '/artistas/sofy/oreja5.png',  tag: 'oreja', label: 'Oreja' },
      { src: '/artistas/sofy/oreja6.png',  tag: 'oreja', label: 'Oreja' },
      { src: '/artistas/sofy/oreja7.jpg',  tag: 'oreja', label: 'Oreja' },
      { src: '/artistas/sofy/oreja8.jpg',  tag: 'oreja', label: 'Oreja' },
      { src: '/artistas/sofy/oreja.heic',  tag: 'oreja', label: 'Oreja' },
      { src: '/artistas/sofy/oreja1.heic', tag: 'oreja', label: 'Oreja' },
      { src: '/artistas/sofy/oreja2.heic', tag: 'oreja', label: 'Oreja' },
      { src: '/artistas/sofy/oreja3.heic', tag: 'oreja', label: 'Oreja' },
      { src: '/artistas/sofy/oreja4.heic', tag: 'oreja', label: 'Oreja' },
      { src: '/artistas/sofy/nariz.jpg',   tag: 'nariz', label: 'Nariz' },
    ],
  },
  {
    slug: 'luis',
    name: 'Luis Aguilar',
    nickname: 'Luis',
    startDate: '2021-02-01',
    styles: ['Black and Gray', 'Realismo', 'Ilustrativo'],
    bio: 'Comencé a tatuar en febrero de 2021 y desde entonces he dedicado mi tiempo a desarrollar mi técnica y encontrar una identidad propia. Actualmente mi enfoque está en crear un estilo inspirado en la estética renacentista aplicada al black and grey, buscando combinar sombras, profundidad y composición artística en cada pieza. Me interesa que cada tatuaje tenga carácter, elegancia y una esencia atemporal.',
    instagram: 'https://www.instagram.com/aguilar.tattoos',
    photo: '/artistas/luis/profilepic.png',
    portfolio: [
      { src: '/artistas/luis/realismo.jpeg',    tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/luis/realismo1.jpeg',   tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/luis/realismo2.jpeg',   tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/luis/realismo3.jpeg',   tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/luis/realismo4.jpeg',   tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/luis/realismo5.jpeg',   tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/luis/realismo6.jpeg',   tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/luis/realismo7.jpeg',   tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/luis/ilustrativo.jpeg',  tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/luis/ilustrativo1.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/luis/ilustrativo2.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/luis/ilustrativo3.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
      { src: '/artistas/luis/ilustrativo4.jpeg', tag: 'ilustrativo', label: 'Ilustrativo' },
    ],
  },
  {
    slug: 'rafa',
    name: 'Rafael Gomez',
    nickname: 'Rafa',
    startDate: '2017-06-01',
    styles: ['Realismo', 'Blackwork'],
    bio: 'Me especializo en el estilo Realismo, en el cual sigo preparándome constantemente ya que es un estilo que te exige muchísimo. Con 9 años tatuando he experimentado y practicado muchos estilos, por lo cual me considero un artista bastante versátil.',
    instagram: 'https://www.instagram.com/rafaelgomez.tattoo',
    photo: '/artistas/rafa/profilepic.png',
    portfolio: [
      { src: '/artistas/rafa/realismogrises.jpeg',  tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/rafa/realismogrises1.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/rafa/realismogrises2.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/rafa/realismogrises3.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/rafa/realismogrises4.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/rafa/realismogrises5.jpeg', tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/rafa/realismocolor.jpeg',   tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/rafa/realismocolor1.jpeg',  tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/rafa/realismocolor2.jpeg',  tag: 'realismo', label: 'Realismo' },
      { src: '/artistas/rafa/blackwork.jpeg',       tag: 'blackwork', label: 'Blackwork' },
      { src: '/artistas/rafa/blackwork1.jpeg',      tag: 'blackwork', label: 'Blackwork' },
    ],
  },
]

export function getArtist(slug: string) {
  return artists.find(a => a.slug === slug)
}
